### ISSUE TITLE
Running "WWBD: Create Environment" in vscode repo results in error "6"

### ISSUE THREAD

**Issue by JacksonKearl** [brettcannon/WWBD#18]
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/8586769/166079397-0cca671e-49f5-45f2-af08-4de4b47c4349.png">

**Comment by brettcannon** [comment]
The extension doesn't use the terminal for anything; I create the virtual environment via Python code.

https://github.com/brettcannon/WWBD/blob/fc0cd8b67f0226764b1cd9161493cd0452f3094a/python-src/wwbd/venv.py#L24

Did you paste that command into the terminal and are saying the created virtual environment is broken? Otherwise it looks like your Python install may be busted (the `dyld` means the linker can't find a file it needs).

**Comment by JacksonKearl** [comment]
I put that into terminal based on the error I saw, which said the executing that failed.

**Comment by brettcannon** [comment]
I take it the command was listed in a traceback in the WWBD output channel? If so then it means when your install of Python tried to create a virtual environment it was unable to install pip into it.

How did you install your copy of Python? And is it able to create a virtual environment somewhere else (`python -m venv <name for environment>`)?

Regardless, this isn't due to the extension itself but your installation of Python and how it created the virtual environment.

**Comment by JacksonKearl** [comment]
```
➜  Desktop python -m venv test-venv
zsh: command not found: python
```

I have to use `python3`, I believe this may be the standard for recent MacOS versions.

**Comment by brettcannon** [comment]
Actually, Python has been removed from macOS starting in 12.3, so now there's no standard 😅.

But yes, Python 2 is not supported (see the requirements section of the README). It's also not supported by the Python extension either. 😁

Thanks for figuring out the cause!
